// Mock PostHog for testing
export default {
  init: jest.fn(),
  capture: jest.fn(),
  identify: jest.fn(),
  reset: jest.fn(),
  isFeatureEnabled: jest.fn(() => false),
  onFeatureFlags: jest.fn(),
  getFeatureFlag: jest.fn(),
  group: jest.fn(),
  alias: jest.fn(),
  set: jest.fn(),
  set_once: jest.fn(),
  register: jest.fn(),
  unregister: jest.fn(),
  opt_in_capturing: jest.fn(),
  opt_out_capturing: jest.fn(),
  has_opted_in_capturing: jest.fn(() => true),
  has_opted_out_capturing: jest.fn(() => false),
  clear_opt_in_out_capturing: jest.fn(),
  debug: jest.fn(),
  people: {
    set: jest.fn(),
    set_once: jest.fn(),
    increment: jest.fn(),
    append: jest.fn(),
    union: jest.fn(),
    track_charge: jest.fn(),
    clear_charges: jest.fn(),
    delete_user: jest.fn(),
  },
}